export const NOTES = ["C", "C#/Db", "D", "D#/Eb", "E", "F", "F#/Gb", "G", "G#/Ab", "A", "A#/Bb", "B"];

export const ROOT_NOTES = [
  { id: 0, name: "C", freq: 130.81 },
  { id: 1, name: "C#/Db", freq: 138.59 },
  { id: 2, name: "D", freq: 146.83 },
  { id: 3, name: "D#/Eb", freq: 155.56 },
  { id: 4, name: "E", freq: 164.81 },
  { id: 5, name: "F", freq: 174.61 },
  { id: 6, name: "F#/Gb", freq: 185.00 },
  { id: 7, name: "G", freq: 196.00 },
  { id: 8, name: "G#/Ab", freq: 207.65 },
  { id: 9, name: "A", freq: 220.00 },
  { id: 10, name: "A#/Bb", freq: 233.08 },
  { id: 11, name: "B", freq: 246.94 },
];

export const INTERVAL_DATA = [
  { id: 0,  name: "1",     desc: "家/绝对稳定", key: "1" },
  { id: 1,  name: "b2",    desc: "极度撕裂纠结", key: "q" },
  { id: 2,  name: "2",     desc: "游荡/悬空感", key: "2" },
  { id: 3,  name: "b3",    desc: "忧郁/黯淡小调", key: "w" },
  { id: 4,  name: "3",     desc: "温暖/阳光大调", key: "3" },
  { id: 5,  name: "4",     desc: "沉重/强迫下坠", key: "4" },
  { id: 6,  name: "b5",    desc: "诡异/危险张力", key: "r" },
  { id: 7,  name: "5",     desc: "开阔/宏伟空旷", key: "5" },
  { id: 8,  name: "b6",    desc: "悲伤/叹息小调", key: "t" },
  { id: 9,  name: "6",     desc: "温和/摇摆小调", key: "6" },
  { id: 10, name: "b7",    desc: "漂浮/现代张力", key: "y" },
  { id: 11, name: "7",     desc: "尖锐/强烈向往", key: "7" },
];

export const PITCH_SPACE = [
  { name: '++1', offset: 24, isBlack: false, isRoot: true, cls: 'root-anchor', isMajor: true, isMinor: true },
  { name: '+7', offset: 23, isBlack: false, cls: 'high-zone', isMajor: true, isMinor: false },
  { name: '+b7', offset: 22, isBlack: true, cls: 'high-zone', isMajor: false, isMinor: true },
  { name: '+6', offset: 21, isBlack: false, cls: 'high-zone', isMajor: true, isMinor: false },
  { name: '+b6', offset: 20, isBlack: true, cls: 'high-zone', isMajor: false, isMinor: true },
  { name: '+5', offset: 19, isBlack: false, cls: 'high-zone', isMajor: true, isMinor: true },
  { name: '+b5', offset: 18, isBlack: true, cls: 'high-zone', isMajor: false, isMinor: false },
  { name: '+4', offset: 17, isBlack: false, cls: 'high-zone', isMajor: true, isMinor: true },
  { name: '+3', offset: 16, isBlack: false, cls: 'high-zone', isMajor: true, isMinor: false },
  { name: '+b3', offset: 15, isBlack: true, cls: 'high-zone', isMajor: false, isMinor: true },
  { name: '+2', offset: 14, isBlack: false, cls: 'high-zone', isMajor: true, isMinor: true },
  { name: '+b2', offset: 13, isBlack: true, cls: 'high-zone', isMajor: false, isMinor: false },
  { name: '+1', offset: 12, isBlack: false, isRoot: true, cls: 'root-anchor', isMajor: true, isMinor: true },
  { name: '7', offset: 11, isBlack: false, cls: '', isMajor: true, isMinor: false },
  { name: 'b7', offset: 10, isBlack: true, cls: '', isMajor: false, isMinor: true },
  { name: '6', offset: 9, isBlack: false, cls: '', isMajor: true, isMinor: false },
  { name: 'b6', offset: 8, isBlack: true, cls: '', isMajor: false, isMinor: true },
  { name: '5', offset: 7, isBlack: false, cls: '', isMajor: true, isMinor: true },
  { name: 'b5', offset: 6, isBlack: true, cls: '', isMajor: false, isMinor: false },
  { name: '4', offset: 5, isBlack: false, cls: '', isMajor: true, isMinor: true },
  { name: '3', offset: 4, isBlack: false, cls: '', isMajor: true, isMinor: false },
  { name: 'b3', offset: 3, isBlack: true, cls: '', isMajor: false, isMinor: true },
  { name: '2', offset: 2, isBlack: false, cls: '', isMajor: true, isMinor: true },
  { name: 'b2', offset: 1, isBlack: true, cls: '', isMajor: false, isMinor: false },
  { name: '1', offset: 0, isBlack: false, isRoot: true, cls: 'root-anchor', isMajor: true, isMinor: true },
  { name: '-7', offset: -1, isBlack: false, cls: 'low-zone', isMajor: true, isMinor: false },
  { name: '-b7', offset: -2, isBlack: true, cls: 'low-zone', isMajor: false, isMinor: true },
  { name: '-6', offset: -3, isBlack: false, cls: 'low-zone', isMajor: true, isMinor: false },
  { name: '-b6', offset: -4, isBlack: true, cls: 'low-zone', isMajor: false, isMinor: true },
  { name: '-5', offset: -5, isBlack: false, cls: 'low-zone', isMajor: true, isMinor: true },
  { name: '-b5', offset: -6, isBlack: true, cls: 'low-zone', isMajor: false, isMinor: false },
  { name: '-4', offset: -7, isBlack: false, cls: 'low-zone', isMajor: true, isMinor: true },
  { name: '-3', offset: -8, isBlack: false, cls: 'low-zone', isMajor: true, isMinor: false },
  { name: '-b3', offset: -9, isBlack: true, cls: 'low-zone', isMajor: false, isMinor: true },
  { name: '-2', offset: -10, isBlack: false, cls: 'low-zone', isMajor: true, isMinor: true },
  { name: '-b2', offset: -11, isBlack: true, cls: 'low-zone', isMajor: false, isMinor: false },
  { name: '-1', offset: -12, isBlack: false, isRoot: true, cls: 'root-anchor', isMajor: true, isMinor: true },
];
